### ISSUE TITLE
Enable JSON & Time with Timezone test cases

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-standard-library#10]
**Description:**
The JSON & Time with Timezone  tests are not migrated yet from the Ballerina lang repo due to an issue in the initialising script for H2. These tests should be migrated.

**Comment by lahirusamith** [comment]
This PR resolved a issue having when getting json type  json type  https://github.com/ballerina-platform/module-ballerina-sql/pull/136

**Comment by lahirusamith** [comment]
After trying to enable the `time with time zone` and `timestamp with time zone` data type test cases in java.jdbc package for h2 database , it gives an error as bellow.

```log
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Syntax error in SQL statement "CREATE CACHED TABLE ""PUBLIC"".""DATETIMETYPES""(
    ""ROW_ID"" INTEGER NOT NULL,
    ""DATE_TYPE"" DATE,
    ""TIME_TYPE"" TIME,
    ""TIMESTAMP_TYPE"" TIMESTAMP,
    ""DATETIME_TYPE"" DATETIME,
    ""TIMEWITHTZ_TYPE"" TIME WITH[*] TIME ZONE,
    ""TIMESTAMPWITHTZ_TYPE"" TIMESTAMP WITH TIME ZONE
)"; expected "(, WITHOUT, FOR, UNSIGNED, INVISIBLE, VISIBLE, NOT, NULL, AS, DEFAULT, GENERATED, ON, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE CACHED TABLE "PUBLIC"."DATETIMETYPES"(
    "ROW_ID" INTEGER NOT NULL,
    "DATE_TYPE" DATE,
    "TIME_TYPE" TIME,
    "TIMESTAMP_TYPE" TIMESTAMP,
    "DATETIME_TYPE" DATETIME,
    "TIMEWITHTZ_TYPE" TIME WITH TIME ZONE,
    "TIMESTAMPWITHTZ_TYPE" TIMESTAMP WITH TIME ZONE
) [42001-199]
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:597)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:576)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.ballerinalang.sql.datasource.SQLDatasource.buildNonXADataSource(SQLDatasource.java:351)
        at org.ballerinalang.sql.datasource.SQLDatasource.<init>(SQLDatasource.java:79)
        at org.ballerinalang.sql.datasource.SQLDatasource.createAndInitDatasource(SQLDatasource.java:235)
        at org.ballerinalang.sql.datasource.SQLDatasource.lambda$retrieveDatasource$1(SQLDatasource.java:149)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at org.ballerinalang.sql.datasource.SQLDatasource.retrieveDatasource(SQLDatasource.java:148)
        at org.ballerinalang.sql.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:58)
        at org.ballerinalang.jdbc.nativeimpl.ClientProcessor.createClient(ClientProcessor.java:75)
        at ballerinax.java$0046jdbc.0_6_0-alpha8.client.createClient(client.bal:147)
        at ballerinax.java$0046jdbc.0_6_0-alpha8.$value$Client.init(client.bal:44)
        at ballerinax.java$0046jdbc.0_6_0-alpha8.$value$Client.call(client.bal)
        at ballerinax.java$0046jdbc.0_6_0-alpha8.$value$Client.$init$(client.bal:22)
        at ballerinax.java$0046jdbc.0_6_0-alpha8.$value$Client.call(client.bal)
        at ballerinax.java$0046jdbc.0_6_0-alpha8.tests.complex-query-test.testColumnAlias(tests/complex-query-test.bal:284)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.lambda$runOnSchedule$0(TesterinaFunction.java:109)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE CACHED TABLE ""PUBLIC"".""DATETIMETYPES""(
    ""ROW_ID"" INTEGER NOT NULL,
    ""DATE_TYPE"" DATE,
    ""TIME_TYPE"" TIME,
    ""TIMESTAMP_TYPE"" TIMESTAMP,
    ""DATETIME_TYPE"" DATETIME,
    ""TIMEWITHTZ_TYPE"" TIME WITH[*] TIME ZONE,
    ""TIMESTAMPWITHTZ_TYPE"" TIMESTAMP WITH TIME ZONE
)"; expected "(, WITHOUT, FOR, UNSIGNED, INVISIBLE, VISIBLE, NOT, NULL, AS, DEFAULT, GENERATED, ON, NOT, NULL, AUTO_INCREMENT, BIGSERIAL, SERIAL, IDENTITY, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, PRIMARY, UNIQUE, NOT, NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE CACHED TABLE "PUBLIC"."DATETIMETYPES"(
    "ROW_ID" INTEGER NOT NULL,
    "DATE_TYPE" DATE,
    "TIME_TYPE" TIME,
    "TIMESTAMP_TYPE" TIMESTAMP,
    "DATETIME_TYPE" DATETIME,
    "TIMEWITHTZ_TYPE" TIME WITH TIME ZONE,
    "TIMESTAMPWITHTZ_TYPE" TIMESTAMP WITH TIME ZONE
) [42001-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.getSyntaxError(DbException.java:243)
        at org.h2.command.Parser.getSyntaxError(Parser.java:991)
        at org.h2.command.Parser.read(Parser.java:4549)
        at org.h2.command.Parser.readIfMore(Parser.java:1391)
        at org.h2.command.Parser.parseCreateTable(Parser.java:7833)
        at org.h2.command.Parser.parseCreate(Parser.java:5818)
        at org.h2.command.Parser.parsePrepared(Parser.java:846)
        at org.h2.command.Parser.parse(Parser.java:788)
        at org.h2.command.Parser.parse(Parser.java:764)
        at org.h2.command.Parser.prepare(Parser.java:667)
        at org.h2.engine.Session.prepare(Session.java:592)
        at org.h2.engine.Session.prepare(Session.java:576)
        at org.h2.engine.MetaRecord.execute(MetaRecord.java:58)
        at org.h2.engine.Database.open(Database.java:842)
        at org.h2.engine.Database.openDatabase(Database.java:319)
        at org.h2.engine.Database.<init>(Database.java:313)
        at org.h2.engine.Engine.openSession(Engine.java:69)
        at org.h2.engine.Engine.openSession(Engine.java:201)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
        at org.h2.engine.Engine.createSession(Engine.java:161)
        at org.h2.engine.Engine.createSession(Engine.java:31)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
        at org.h2.Driver.connect(Driver.java:69)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
        ... 25 more
```
There is nothing wrong with the table creation query because I tried to execute the sql query manually using h2 database driver (h2-1.4.200.jar) and successfully created a table in a h2 database. 
```sql 
CREATE TABLE IF NOT EXISTS DateTimeTypes(
   row_id         INTEGER NOT NULL,
   date_type      DATE,
   time_type      TIME,
   timestamp_type timestamp,
   datetime_type  datetime,
   timewithtz_type TIME WITH TIME ZONE,
   timestampwithtz_type TIMESTAMP WITH TIME ZONE,
   PRIMARY KEY (row_id)
);

Insert into DateTimeTypes (row_id, date_type, time_type, timestamp_type, datetime_type, timewithtz_type, timestampwithtz_type)
     values (1,'2017-05-23','14:15:23','2017-01-25 16:33:55','2017-01-25 16:33:55', '23:15:23+8:30','2017-01-25 16:33:55-2:30');

```

the above mentioned issue is coming as we are trying to create the db client using java.jdbc:Client and it may because H2 database driver is not fully compatible with hikariCP when it comes to TIME WITH TIME ZONE and TIMESTAMP WITH TIME ZONE data types.

**Comment by BuddhiWathsala** [comment]
Closing this issue since the H2 database not support time with timezones as per the aforementioned comment.
