### ISSUE TITLE
Possible java.lang.IndexOutOfBoundsException in the plugin code

### ISSUE THREAD

**Issue by gimantha** [ballerina-platform/ballerina-standard-library#101]
Note sure if this is a duplicate issue..
If the parameter count is 0, then the following code will throw a java.lang.IndexOutOfBoundsException at `parameters.get(0)`

https://github.com/wso2-ballerina/module-ftp/blob/5a6b9e94112aba9a2906c85a2b89c6fd4da9eef8/ftp-compiler-plugin/src/main/java/org/wso2/ei/b7a/ftp/plugin/FTPCompilerPlugin.java#L81

[2020-01-09 11:57:01,230] SEVERE {b7a.log.crash} - Index: 0, Size: 0 
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at org.wso2.ei.b7a.ftp.plugin.FTPCompilerPlugin.process(FTPCompilerPlugin.java:81)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$10(CompilerPluginRunner.java:182)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.invokeServiceProcessor(CompilerPluginRunner.java:365)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.notifyServiceTypeProcessors(CompilerPluginRunner.java:334)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:181)
	at org.wso2.ballerinalang.compiler.tree.BLangService.accept(BLangService.java:139)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$2(CompilerPluginRunner.java:136)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:136)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:124)
	at org.wso2.ballerinalang.compiler.CompilerDriver.annotationProcess(CompilerDriver.java:287)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:249)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:216)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:131)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:173)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:178)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:93)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:101)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:51)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:395)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:59)

**Comment by Bhashinee** [comment]
Closing the issue as this is no longer valid with new FTP design and implementation.
