### ISSUE TITLE
Unable to Connect to SFTP with private key - user not assignable

### ISSUE THREAD

**Issue by jimk-osu** [ballerina-platform/ballerina-standard-library#109]
**Description:**
Unable to connect to SFTP Server using `PrivateKey`

Current code:

```ballerina
import ballerina/http;
import ballerina/io;
import ballerina/log;
import ballerina/config;
import wso2/ftp;

ftp:ClientEndpointConfig ftpConfig = {
    protocol: ftp:SFTP,
    host: "somesftp",
    port: 22,
    secureSocket: {
        privateKey: {
            path: "/home/someUser/.ssh/id_rsa"
        } // Values allowed: wso2/ftp:0.0.0:PrivateKey|()
    }
};
ftp:Client ftpClient = new(ftpConfig);

public function main(string... args) {
    var listResult = ftpClient->list("/out/processed");
    if (listResult is string[]) {
        foreach string file in listResult {
            io:println("File: " + file);
        }
    } else {
        io:println("An error occured.", listResult);
        return;
    }
}
```

`ballerina-internal.log` error:

```
[2019-08-22 11:16:28,641] ERROR {org.ballerinalang.ftp.client.actions.List$FTPFileListListener} - Could not connect to SFTP server at "sftp://somesftp/". 
org.apache.commons.vfs2.FileSystemException: Could not connect to SFTP server at "sftp://sftp.service.osu.edu/".
	at org.apache.commons.vfs2.provider.sftp.SftpFileProvider.doCreateFileSystem(SftpFileProvider.java:86)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.getFileSystem(AbstractOriginatingFileProvider.java:149)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:111)
	at org.apache.commons.vfs2.provider.AbstractOriginatingFileProvider.findFile(AbstractOriginatingFileProvider.java:81)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:778)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.resolveFile(DefaultFileSystemManager.java:658)
	at org.wso2.transport.remotefilesystem.client.connector.contractimpl.VFSClientConnectorImpl.send(VFSClientConnectorImpl.java:72)
	at org.ballerinalang.ftp.client.actions.List.execute(List.java:77)
	at org.ballerinalang.bre.bvm.BlockingNativeCallableUnit.execute(BlockingNativeCallableUnit.java:35)
	at org.ballerinalang.bre.bvm.BVM.invokeNativeCallable(BVM.java:896)
	at org.ballerinalang.bre.bvm.BVM.invokeCallable(BVM.java:858)
	at org.ballerinalang.bre.bvm.BVM.invokeVirtualFunction(BVM.java:3348)
	at org.ballerinalang.bre.bvm.BVM.execute(BVM.java:428)
	at org.ballerinalang.bre.bvm.BVMScheduler.execute(BVMScheduler.java:72)
	at org.ballerinalang.bre.bvm.BVMExecutor.execute(BVMExecutor.java:184)
	at org.ballerinalang.bre.bvm.BVMExecutor.executeEntryFunction(BVMExecutor.java:92)
	at org.ballerinalang.BLangProgramRunner.runMainFunc(BLangProgramRunner.java:75)
	at org.ballerinalang.launcher.LauncherUtils.runMain(LauncherUtils.java:114)
	at org.ballerinalang.launcher.LauncherUtils.runBal(LauncherUtils.java:413)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:106)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:267)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:63)
Caused by: org.apache.commons.vfs2.FileSystemException: Could not connect to SFTP server at "sftp.service.osu.edu".
	at org.apache.commons.vfs2.provider.sftp.SftpClientFactory.createConnection(SftpClientFactory.java:164)
	at org.apache.commons.vfs2.provider.sftp.SftpFileProvider.doCreateFileSystem(SftpFileProvider.java:79)
	... 22 more
Caused by: java.lang.NullPointerException
	at java.lang.String.<init>(String.java:166)
	at org.apache.commons.vfs2.provider.sftp.SftpClientFactory.createConnection(SftpClientFactory.java:92)
	... 23 more
 
```

I'm able to connect to this SFTP site with a private key via `sftp` and using a GUI based tool like Cyberduck or Filezilla. The main difference I'm seeing between these configurations and ballerina is that both of these allow for user designation + private key where this [library](https://github.com/wso2-ballerina/module-ftp/blob/4bacdb2bb97c714945073c2d5c2c31d35a71d10d/component/src/main/ballerina/ftp/commons.bal#L49) only allows for private key path and password.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
`Ballerina 0.991.0`

**OS, DB, other environment details and versions:**    
`Darwin`
**Steps to reproduce:**

**Related Issues:**

**Comment by Maninda** [comment]
In the latest `master` branch of FTP module, SFTP is working with private key in test case [1]. The SFTP configuration is as [2].

```ballerina
ftp:ClientConfiguration sftpConfig = {
    protocol: ftp:SFTP,
    host: <HOST_ADDRESS_OR_IP_ADDRESS>,
    port: <PORT>,
    auth: {
        basicAuth: {username: <USERNAME>, password: <PASSWORD>},
        privateKey: {
            path: <PRIVATE_KEY_FILE_LOCATION>,
            password: <PRIVATE_KEY_PASSWORD>
        }
    }
};
```

The above configuration is for two factor authentication with both `basicAuth` and `privateKey`. If the server is only supporting one of them, only one of these configurations is sufficient.

[1] https://github.com/ballerina-platform/module-ballerina-ftp/blob/2520384c6d3e9f067930c69d0cc934acbf179d9e/ftp-ballerina/tests/secure_client_endpoint_test.bal#L25
[2] https://github.com/ballerina-platform/module-ballerina-ftp/blob/2520384c6d3e9f067930c69d0cc934acbf179d9e/ftp-ballerina/tests/client_endpoint_test.bal#L40
