### ISSUE TITLE
HttpClient call get blocked if code get panic inside http resource

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-standard-library#1141]
**Description:**
```

service / on new http:Listener(8080) {
    resource function post files(http:Caller caller, http:Request req) returns string {
        map<string[]> queryParams = req.getQueryParams();
        string[] fileName = queryParams.get("fileName");
        string filePath = checkpanic file:joinPath(directoryPath, fileName[0]);
        checkpanic file:create(filePath);
        return "File is created successfully";
    }
}

```

If I send http request with same filename twice, secod request get blocked due to file already exsit. But should I get http response error for panic cases.

sample request

 curl -X POST localhost:8080/files?fileName=newfilename

**Comment by chamil321** [comment]
Reason for not getting the response is that, when handing the error, there is following NPE which reported in #1167 
```
[2021-06-08 11:20:41,439] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.ballerinalang.net.http.HttpUtil.getErrorMessage(HttpUtil.java:485)
	at org.ballerinalang.net.http.HttpUtil.handleFailure(HttpUtil.java:477)
	at org.ballerinalang.net.http.HttpCallableUnitCallback.sendFailureResponse(HttpCallableUnitCallback.java:92)
	at org.ballerinalang.net.http.HttpCallableUnitCallback.notifyFailure(HttpCallableUnitCallback.java:88)
	at io.ballerina.runtime.internal.scheduling.Scheduler.postProcess(Scheduler.java:387)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:343)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:295)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
