### ISSUE TITLE
Providing an invalid log level gives a bad sad error

### ISSUE THREAD

**Issue by madushajg** [ballerina-platform/ballerina-standard-library#1188]
**Description:**
When providing an invalid log level, the program gives a bad sad error at the runtime.

Ex:
```
[ballerina.log]
level="debug"
```

Error stack:
```
[2021-03-31 13:27:45,104] SEVERE {b7a.log.crash} - invalid log level: debug 
java.lang.RuntimeException: invalid log level: debug
	at org.ballerinalang.logging.util.BLogLevel.toBLogLevel(BLogLevel.java:45)
	at org.ballerinalang.stdlib.log.Utils.setGlobalLogLevelExtern(Utils.java:109)
	at ballerina.log.1_1_0-alpha6.natives.setGlobalLogLevelExtern(natives.bal:174)
	at ballerina.log.1_1_0-alpha6.natives.initializeLogLevels(natives.bal:168)
	at ballerina.log.1_1_0-alpha6.init.init(init.bal:21)
	at ballerina.log.1_1_0-alpha6.$_init.$gen$$0046$0060init$0062(log:1)
	at madushagunasekara.proj.0_1_0.$_init.$moduleInit(proj)
	at madushagunasekara.proj.0_1_0.$_init.$lambda$$moduleInit$(proj)
	at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:571)
	at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:301)
	at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:269)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**
Provide an invalid log level in `Config.toml` and run the program.

**Affected Versions:**
Ballerina Swan Lake Alpha4

**Comment by MadhukaHarith92** [comment]
@madushajg , is throwing a runtime error instead of a bad sad error be sufficient for the requirement?

**Comment by madushajg** [comment]
Instead of throwing a runtime error, shall we print a log like the below at the runtime?
```
invalid log level: debug
```
