### ISSUE TITLE
Building the grpc module with -x check flag disables running tests

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/ballerina-standard-library#1283]
**Description:**
$Subject

**Steps to reproduce:**
1. Clone `grpc` module (https://github.com/ballerina-platform/module-ballerina-grpc)
2. Build the module by running the below command.
```
./gradlew clean build -x check
```

**Affected Versions:**
Latest master

**OS, DB, other environment details and versions:**
MacOS

**Comment by MadhukaHarith92** [comment]
The following is also observed. After building the module, a bad sad error gets thrown.
```
[2021-04-27 09:43:09,526] SEVERE {b7a.log.crash} - java.nio.file.FileSystemException: /Users/harith/Ballerina/ballerina-platform/module-ballerina-grpc/grpc-ballerina/target/cache/tests_cache/coverage/bcprov-jdk15on-1.61.jar/org/bouncycastle/jcajce/provider/drbg/DRBG$HybridSecureRandom$SignallingEntropySource.class -> /Users/harith/Ballerina/ballerina-platform/module-ballerina-grpc/grpc-ballerina/target/cache/tests_cache/coverage/bin/grpc/0.8.0-alpha9/eac/asn1/smime/crmf/asn1/misc/cmc/asn1/ntt/asn1/cmp/asn1/mozilla/asn1/ua/asn1/iso/asn1/util/asn1/nsri/asn1/bc/asn1/sec/tsp/asn1/anssi/asn1/microsoft/asn1/kisa/asn1/x9/asn1/nist/asn1/gnu/edec/asn1/x509/qualified/x509/sigi/x509/isismtt/x509/ocsp/x500/style/x500/asn1/cms/ecc/cms/asn1/dvcs/asn1/esf/asn1/ess/est/asn1/gm/asn1/icao/iana/asn1/ocsp/asn1/cryptopro/asn1/cryptlib/asn1/bsi/pkcs/asn1/oiw/asn1/teletrust/rosstandart/asn1/crypto/encodings/crypto/paddings/crypto/parsers/crypto/modes/kgcm/modes/gcm/modes/commitments/crypto/util/crypto/io/ec/crypto/kdf/agreement/jpake/agreement/srp/agreement/crypto/kems/crypto/prng/drbg/prng/crypto/tls/crypto/engines/examples/crypto/params/crypto/digests/macs/generators/crypto/signers/crypto/jcajce/util/jcajce/io/jcajce/spec/symmetric/util/symmetric/keystore/pkcs12/bc/keystore/bcfks/util/config/digest/drbg/DRBG$HybridSecureRandom$SignallingEntropySource.class: File name too long 
java.lang.RuntimeException: java.nio.file.FileSystemException: /Users/harith/Ballerina/ballerina-platform/module-ballerina-grpc/grpc-ballerina/target/cache/tests_cache/coverage/bcprov-jdk15on-1.61.jar/org/bouncycastle/jcajce/provider/drbg/DRBG$HybridSecureRandom$SignallingEntropySource.class -> /Users/harith/Ballerina/ballerina-platform/module-ballerina-grpc/grpc-ballerina/target/cache/tests_cache/coverage/bin/grpc/0.8.0-alpha9/eac/asn1/smime/crmf/asn1/misc/cmc/asn1/ntt/asn1/cmp/asn1/mozilla/asn1/ua/asn1/iso/asn1/util/asn1/nsri/asn1/bc/asn1/sec/tsp/asn1/anssi/asn1/microsoft/asn1/kisa/asn1/x9/asn1/nist/asn1/gnu/edec/asn1/x509/qualified/x509/sigi/x509/isismtt/x509/ocsp/x500/style/x500/asn1/cms/ecc/cms/asn1/dvcs/asn1/esf/asn1/ess/est/asn1/gm/asn1/icao/iana/asn1/ocsp/asn1/cryptopro/asn1/cryptlib/asn1/bsi/pkcs/asn1/oiw/asn1/teletrust/rosstandart/asn1/crypto/encodings/crypto/paddings/crypto/parsers/crypto/modes/kgcm/modes/gcm/modes/commitments/crypto/util/crypto/io/ec/crypto/kdf/agreement/jpake/agreement/srp/agreement/crypto/kems/crypto/prng/drbg/prng/crypto/tls/crypto/engines/examples/crypto/params/crypto/digests/macs/generators/crypto/signers/crypto/jcajce/util/jcajce/io/jcajce/spec/symmetric/util/symmetric/keystore/pkcs12/bc/keystore/bcfks/util/config/digest/drbg/DRBG$HybridSecureRandom$SignallingEntropySource.class: File name too long
	at org.ballerinalang.test.runtime.util.CodeCoverageUtils.unzipCompiledSource(CodeCoverageUtils.java:119)
	at org.ballerinalang.test.runtime.entity.CoverageReport.addCompiledSources(CoverageReport.java:229)
	at org.ballerinalang.test.runtime.entity.CoverageReport.generateReport(CoverageReport.java:127)
	at io.ballerina.cli.task.RunTestsTask.generateCoverage(RunTestsTask.java:277)
	at io.ballerina.cli.task.RunTestsTask.execute(RunTestsTask.java:234)
	at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
	at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:272)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
Caused by: java.nio.file.FileSystemException: /Users/harith/Ballerina/ballerina-platform/module-ballerina-grpc/grpc-ballerina/target/cache/tests_cache/coverage/bcprov-jdk15on-1.61.jar/org/bouncycastle/jcajce/provider/drbg/DRBG$HybridSecureRandom$SignallingEntropySource.class -> /Users/harith/Ballerina/ballerina-platform/module-ballerina-grpc/grpc-ballerina/target/cache/tests_cache/coverage/bin/grpc/0.8.0-alpha9/eac/asn1/smime/crmf/asn1/misc/cmc/asn1/ntt/asn1/cmp/asn1/mozilla/asn1/ua/asn1/iso/asn1/util/asn1/nsri/asn1/bc/asn1/sec/tsp/asn1/anssi/asn1/microsoft/asn1/kisa/asn1/x9/asn1/nist/asn1/gnu/edec/asn1/x509/qualified/x509/sigi/x509/isismtt/x509/ocsp/x500/style/x500/asn1/cms/ecc/cms/asn1/dvcs/asn1/esf/asn1/ess/est/asn1/gm/asn1/icao/iana/asn1/ocsp/asn1/cryptopro/asn1/cryptlib/asn1/bsi/pkcs/asn1/oiw/asn1/teletrust/rosstandart/asn1/crypto/encodings/crypto/paddings/crypto/parsers/crypto/modes/kgcm/modes/gcm/modes/commitments/crypto/util/crypto/io/ec/crypto/kdf/agreement/jpake/agreement/srp/agreement/crypto/kems/crypto/prng/drbg/prng/crypto/tls/crypto/engines/examples/crypto/params/crypto/digests/macs/generators/crypto/signers/crypto/jcajce/util/jcajce/io/jcajce/spec/symmetric/util/symmetric/keystore/pkcs12/bc/keystore/bcfks/util/config/digest/drbg/DRBG$HybridSecureRandom$SignallingEntropySource.class: File name too long
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:478)
	at java.base/sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:267)
	at java.base/java.nio.file.Files.move(Files.java:1421)
	at org.ballerinalang.test.runtime.util.CodeCoverageUtils.copyClassFilesToBinPath(CodeCoverageUtils.java:174)
	at org.ballerinalang.test.runtime.util.CodeCoverageUtils.unzipCompiledSource(CodeCoverageUtils.java:111)
	... 8 more
```

This gets fixed after removing the `--code-coverage` flag from th build.gradle (https://github.com/ballerina-platform/module-ballerina-grpc/blob/master/grpc-ballerina/build.gradle#L40)

**Comment by dilanSachi** [comment]
This issue does not appear anymore. All the tests are running and the build successfully passes with `./gradlew clean build -x check`
