### ISSUE TITLE
HTTP compiler plugin fails when the type descriptor is not specified in the listener declaration

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-standard-library#1335]
**Description:**
$title.

**Steps to reproduce:**
```ballerina
import ballerina/http;

// Works
// listener http:Listener ln = new http:Listener(8080);

// Error
listener ln = new http:Listener(8080);

service / on ln {
    resource function get res() returns string => "hello world!";
}
```

```cmd
$ bal run foo.bal 

Compiling source
        foo.bal
error: compilation failed: The compiler extension in package 'ballerina:http:1.1.0-beta.1' failed to complete. null
```

Stack trace from VSCode output
```log
io.ballerina.projects.ProjectException: The compiler extension in package 'ballerina:http:1.1.0-beta.1' failed to complete. null
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxNodeAnalysisTask.perform(CodeAnalyzerManager.java:230)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxTreeVisitor.runAnalysisTasks(CodeAnalyzerManager.java:485)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxTreeVisitor.visitSyntaxNode(CodeAnalyzerManager.java:472)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:63)
	at io.ballerina.compiler.syntax.tree.ServiceDeclarationNode.accept(ServiceDeclarationNode.java:78)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxTreeVisitor.visitSyntaxNode(CodeAnalyzerManager.java:477)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visit(NodeVisitor.java:43)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxTreeVisitor.runAnalysisTasks(CodeAnalyzerManager.java:460)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxNodeAnalysisTaskRunner.runTasks(CodeAnalyzerManager.java:422)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxNodeAnalysisTaskRunner.runTasks(CodeAnalyzerManager.java:411)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxNodeAnalysisTaskRunner.runTasks(CodeAnalyzerManager.java:403)
	at io.ballerina.projects.CodeAnalyzerManager.runSyntaxNodeAnalysisTasks(CodeAnalyzerManager.java:115)
	at io.ballerina.projects.CodeAnalyzerManager.runCodeAnalyzerTasks(CodeAnalyzerManager.java:68)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:107)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:206)
	at io.ballerina.projects.Package.getCompilation(Package.java:132)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:218)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:197)
	at org.ballerinalang.langserver.codeaction.CodeActionRouter.getAvailableCodeActions(CodeActionRouter.java:66)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:46)
	at org.ballerinalang.langserver.codeaction.BallerinaCodeActionExtension.execute(BallerinaCodeActionExtension.java:34)
	at org.ballerinalang.langserver.LangExtensionDelegator.codeActions(LangExtensionDelegator.java:133)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$codeAction$8(BallerinaTextDocumentService.java:336)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at io.ballerina.stdlib.http.compiler.HttpServiceValidator.isListenerBelongsToHttpModule(HttpServiceValidator.java:83)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:538)
	at io.ballerina.stdlib.http.compiler.HttpServiceValidator.perform(HttpServiceValidator.java:59)
	at io.ballerina.stdlib.http.compiler.HttpServiceValidator.perform(HttpServiceValidator.java:50)
	at io.ballerina.projects.CodeAnalyzerManager$SyntaxNodeAnalysisTask.perform(CodeAnalyzerManager.java:223)
	... 29 more
```

**Affected Versions:**
slbeta1-rc1

**Comment by chamil321** [comment]
`((ServiceDeclarationSymbol) serviceSymOptional.get()).listenerTypes()` does not capture this listener pattern.

**Comment by chamil321** [comment]
The fix should come from the lang team. 
- The syntax is not even allowed yet from the compiler.
- The failed compilation continues to stdlib compiler plugins
- The semantic model returns null for the listener type

@pubudu91 @MaryamZi Please note
