### ISSUE TITLE
Client gets blocked when `securesocket` is configured with `enable: false` config

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#1629]
**Description:**
When a `gRPC client` is configured with `https` and securesocket enable config to false, the client does not return any result or end in failure.

**Steps to reproduce:**
Create a client as,
```
HelloWorldClient|grpc:Error result = new ("https://localhost:9091", {
        secureSocket: {
            enable: false
        }
    });
```
And call a service.
**Suggested Labels (optional):**

module/grpc,

**Comment by BuddhiWathsala** [comment]
This happens when the server enables mutual SSL and the client disables the cert validation.

There is a netty level exception that has been throwing. But it cannot be caught on Ballerina side because we call the RPC and return without expecting a response. The responses will be taken using a listener, but before that, the exception will throw and reach a hanging state.

```sh
javax.net.ssl.SSLHandshakeException: error:100000c0:SSL routines:OPENSSL_internal:PEER_DID_NOT_RETURN_A_CERTIFICATE
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1334)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1295)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1371)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1414)
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:224)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1338)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
@ldclakmal @Bhashinee did you encounter such a case in HTTP?

**Comment by BuddhiWathsala** [comment]
I faced a similar issue in the HTTP library as well. Here, I tried an HTTP2 sample with mutual SSL as follows.

#### HTTP2 Server
```ballerina
import ballerina/http;

const string PUBLIC_CRT_PATH = "public.crt";
const string PRIVATE_KEY_PATH = "private.key";

listener http:Listener securedEP = new(9090,
    secureSocket = {
        key: {
            certFile: PUBLIC_CRT_PATH,
            keyFile: PRIVATE_KEY_PATH
        },

        mutualSsl: {
            verifyClient: http:REQUIRE,
            cert: PUBLIC_CRT_PATH
        },

        protocol: {
            name: http:TLS,
            versions: ["TLSv1.2", "TLSv1.1"]
        },

        ciphers: ["TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA"]

    },
    httpVersion = "2.0"
);

service /foo on securedEP {
    resource function get bar() returns string {
        return "Hello, World!";
    }
}
```

#### HTTP2 Client 

```ballerina
import ballerina/http;
import ballerina/io;

const string PUBLIC_CRT_PATH = "public.crt";
const string PRIVATE_KEY_PATH = "private.key";

http:Client ep = check new ("https://localhost:9090", {
    secureSocket: {
        cert: PUBLIC_CRT_PATH,
        key: {
            certFile: PUBLIC_CRT_PATH,
            keyFile: PRIVATE_KEY_PATH
        },
        enable: false
    },
    httpVersion: "2.0"
});

public function main() returns error? {
    json j = check ep->get("/foo/bar");
    io:println(j);
}
```

When I ran the aforementioned example, the client was hanging without any error. This might be an HTTP transport level issue.

**Comment by ldclakmal** [comment]
This need to be checked and fixed on top of https://github.com/ballerina-platform/module-ballerina-grpc/pull/355
