### ISSUE TITLE
Warning: Detected conflicting jar files in ballerina/sql & 'ballerinax/mysql

### ISSUE THREAD

**Issue by hevayo** [ballerina-platform/ballerina-standard-library#1636]
**Description:**
I am getting following warning when using mysql module 
```
warning: Detected conflicting jar files:
        'sql-native-0.6.0-beta.2-20210630-212800-2903cac.jar' dependency of 'ballerina/sql' conflict with 'sql-native-0.6.0-beta.2.jar' dependency of 'ballerinax/mysql'
```
It seems the same jar is included in two modules. is it required or can we remove the native lib from one module so that the warning will go away.

Affected versions beta2

**Comment by niveathika** [comment]
@hevayo Even though we get the warning, if we don't include the native SQL jar, we are getting a class not found exception,
```
java.lang.NoClassDefFoundError: io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessor
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
        at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3191)
        at java.base/java.lang.Class.getMethods(Class.java:1904)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.getExecutables(JMethodResolver.java:787)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.resolveByMethodName(JMethodResolver.java:143)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.JMethodResolver.resolve(JMethodResolver.java:107)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropValidator.validateAndGetJMethod(InteropValidator.java:195)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropValidator.createJInteropFunction(InteropValidator.java:215)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropValidator.getBirFunction(InteropValidator.java:202)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropValidator.validateTypeAttachedFunctions(InteropValidator.java:157)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropValidator.validateFunctions(InteropValidator.java:123)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropValidator.validateModulePackages(InteropValidator.java:93)
        at org.wso2.ballerinalang.compiler.bir.codegen.interop.InteropValidator.validate(InteropValidator.java:73)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:295)
        at io.ballerina.projects.ModuleContext.generateCodeInternal(ModuleContext.java:407)
        at io.ballerina.projects.ModuleCompilationState$4.generatePlatformSpecificCode(ModuleCompilationState.java:132)
        at io.ballerina.projects.ModuleContext.generatePlatformSpecificCode(ModuleContext.java:333)
        at io.ballerina.projects.JBallerinaBackend.performCodeGen(JBallerinaBackend.java:157)
        at io.ballerina.projects.JBallerinaBackend.<init>(JBallerinaBackend.java:141)
        at io.ballerina.projects.JBallerinaBackend.lambda$from$0(JBallerinaBackend.java:115)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.ballerina.projects.PackageCompilation.getCompilerBackend(PackageCompilation.java:150)
        at io.ballerina.projects.JBallerinaBackend.from(JBallerinaBackend.java:114)
        at io.ballerina.cli.task.CompileTask.execute(CompileTask.java:65)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:302)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
Caused by: java.lang.ClassNotFoundException: io.ballerina.stdlib.sql.parameterprocessor.DefaultResultParameterProcessor
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 29 more
```

**Comment by niveathika** [comment]
Here the dependency is needed in both SQL and MySQL modules, SQL for the use in OutParameter calls and MySQL for operations.

It was discussed and decided to allow this (Within patch version changes)
