### ISSUE TITLE
TLSv1.0 does not support in HTTP2 with mutual SSL

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1724]
**Description:**
```
java.lang.IllegalArgumentException: Protocol TLSv1.0 is not supported.
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.setEnabledProtocols0(ReferenceCountedOpenSslEngine.java:1702)
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.<init>(ReferenceCountedOpenSslEngine.java:343)
        at io.netty.handler.ssl.OpenSslEngine.<init>(OpenSslEngine.java:32)
        at io.netty.handler.ssl.OpenSslContext.newEngine0(OpenSslContext.java:51)
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.newHandler(ReferenceCountedOpenSslContext.java:406)
        at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:952)
        at io.ballerina.stdlib.http.transport.contractimpl.listener.HttpServerChannelInitializer.initChannel(HttpServerChannelInitializer.java:132)
        at io.ballerina.stdlib.http.transport.contractimpl.listener.HttpServerChannelInitializer.initChannel(HttpServerChannelInitializer.java:82)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Happens in Ballerina SL 2.0.

**Steps to Reproduce**
##### Server
```ballerina
import ballerina/http;

const string PUBLIC_CRT_PATH = "public.crt";
const string PRIVATE_KEY_PATH = "private.key";

listener http:Listener securedEP = new(9090,
    secureSocket = {
        key: {
            certFile: PUBLIC_CRT_PATH,
            keyFile: PRIVATE_KEY_PATH
        },

        mutualSsl: {
            verifyClient: http:REQUIRE,
            cert: PUBLIC_CRT_PATH
        },

        protocol: {
            name: http:TLS,
            versions: ["TLSv1.1"]
        }

    },
    httpVersion = "2.0"
);
service /foo on securedEP {
    resource function get bar() returns string {
        return "Hello, World!";
    }
}
```

##### Client
```ballerina
import ballerina/http;
import ballerina/io;

const string PUBLIC_CRT_PATH = "public.crt";
const string PRIVATE_KEY_PATH = "private.key";

http:Client ep = check new ("https://localhost:9090", {
    secureSocket: {
        key: {
            certFile: PUBLIC_CRT_PATH,
            keyFile: PRIVATE_KEY_PATH
        },
        enable: false,
        protocol: {
            name: http:TLS,
            versions: ["TLSv1.0"]
        }
    },
    httpVersion: "2.0"
});

public function main() returns error? {
    json j = check ep->get("/foo/bar");
    io:println(j);
}
```

**Comment by Bhashinee** [comment]
According to the HTTP2 spec, it requires TLS1.2 or a higher version. 
https://datatracker.ietf.org/doc/html/rfc9113#section-9.2

Hence closing the issue.
