### ISSUE TITLE
Getting NPE with HTTP tracing

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#1834]
**Description:**
I tried a simple HTTP service enabling tracing and it throws the following null pointer exception.

```sh
java.util.logging.ErrorManager: 5
java.lang.NullPointerException
        at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
        at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
        at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
        at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
        at java.base/java.util.Formatter.parse(Formatter.java:2700)
        at java.base/java.util.Formatter.format(Formatter.java:2655)
        at java.base/java.util.Formatter.format(Formatter.java:2609)
        at java.base/java.lang.String.format(String.java:2897)
        at io.ballerina.stdlib.http.api.logging.formatters.HttpTraceLogFormatter.format(HttpTraceLogFormatter.java:52)
        at java.logging/java.util.logging.StreamHandler.publish(StreamHandler.java:199)
        at java.logging/java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:95)
        at java.logging/java.util.logging.Logger.log(Logger.java:979)
        at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:582)
        at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:632)
        at io.netty.util.internal.logging.LocationAwareSlf4JLogger.log(LocationAwareSlf4JLogger.java:42)
        at io.netty.util.internal.logging.LocationAwareSlf4JLogger.trace(LocationAwareSlf4JLogger.java:61)
        at io.netty.util.internal.logging.AbstractInternalLogger.log(AbstractInternalLogger.java:142)
        at io.netty.handler.logging.LoggingHandler.channelRegistered(LoggingHandler.java:171)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:166)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:152)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:145)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1383)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:166)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:152)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:815)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:517)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**
##### HTTP Sample
```ballerina
import ballerina/http;
service / on new http:Listener(9090) {
    resource function get greeting() returns string {
        return "Hello, World!";
    }
}
```

##### Configurations
`Config.toml` file.
```toml
[ballerina.http.traceLogAdvancedConfig]
console = true              
path = "testTraceLog.txt" 
```

**Affected Versions:**
SL Beta 2

**OS, DB, other environment details and versions:**
- macOS
- Java 11

@chamil321 @TharmiganK any idea about this?.

**Comment by TharmiganK** [comment]
The reason for this error is that the trace log format defined in the `logging.properties` file is not read by the module. Fixed this issue in PR: [`Load logging.properties from the classpath`](https://github.com/ballerina-platform/module-ballerina-http/pull/602)
