### ISSUE TITLE
gRPC CLI failed to generate nested protos

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-standard-library#2711]
**Description:**
When I try to generate a stub file with a proto file with nested dependencies, it gives the following error.

```sh
➜  proto bal grpc --input ./messages/grpc/ballerina/hello.proto --output . --proto-path .
Continuing with the existing protoc executor file at /var/folders/jq/ps0xmq910yv6mqfpqk5w6zd00000gp/T/protoc-3.9.1-osx-x86_64.exe
Successfully extracted the library files.
Feb 21, 2022 9:45:59 AM io.ballerina.stdlib.grpc.protobuf.cmd.GrpcCmd generateBalFile
SEVERE: An error occurred when generating the dependent proto descriptor. 
/var/folders/jq/ps0xmq910yv6mqfpqk5w6zd00000gp/T/message.proto: No such file or directory
io.ballerina.stdlib.grpc.protobuf.exception.CodeGeneratorException: 
/var/folders/jq/ps0xmq910yv6mqfpqk5w6zd00000gp/T/message.proto: No such file or directory
        at io.ballerina.stdlib.grpc.protobuf.utils.BalFileGenerationUtils.generateDescriptor(BalFileGenerationUtils.java:81)
        at io.ballerina.stdlib.grpc.protobuf.cmd.DescriptorsGenerator.generateDependentDescriptor(DescriptorsGenerator.java:90)
        at io.ballerina.stdlib.grpc.protobuf.cmd.GrpcCmd.generateBalFile(GrpcCmd.java:271)
        at io.ballerina.stdlib.grpc.protobuf.cmd.GrpcCmd.execute(GrpcCmd.java:156)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)

An error occurred when generating the dependent proto descriptor. 
/var/folders/jq/ps0xmq910yv6mqfpqk5w6zd00000gp/T/message.proto: No such file or directory
```

Directory structure.

```sh
➜  proto tree .
.
├── message.proto
└── messages
    └── grpc
        └── ballerina
            └── hello.proto
```

The stub files that I used to generate is as follows.

**hello.proto**

```proto
syntax = "proto3";

import "google/protobuf/wrappers.proto";
import "message.proto";

service helloWorld {
	rpc hello(google.protobuf.StringValue) returns (Response);
}
```

**message.proto**
```proto
syntax = "proto3";

message Response {
    string say = 1;
}
```

Also attached protos as a zip here.
[proto.zip](https://github.com/ballerina-platform/ballerina-standard-library/files/8106169/proto.zip)

**Affected Versions:**
- SL GA
- gRPC Ballerina 1.2.0

**OS, DB, other environment details and versions:**
- macOS
- Java 11

**Comment by BuddhiWathsala** [comment]
Here, my actual use case is to generate stub files for the following proto definition.
https://github.com/envoyproxy/java-control-plane/blob/v0.1.30/api/src/main/proto/envoy/service/discovery/v3/ads.proto

**Comment by dilanSachi** [comment]
This is working successfully for both the mentioned usecases.
* bal grpc --input ./messages/grpc/ballerina/hello.proto --output . --proto-path .
* bal grpc --input ./envoy/service/discovery/v3/ads.proto --output . --proto-path .
Hence closing
