### ISSUE TITLE
`ftp` service  `onFileChange` fails when the listener is binded dynamically

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#2793]
**Description:**
When an `ftp` service object is created and a listener is binded dynamically, an exception is thrown,
```
[2022-03-16 17:48:39,005] SEVERE {b7a.log.crash} - Index 2 out of bounds for length 2 
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at dilan.ftp_tooling_test.0.$value$$anonType$_0.call(main.bal)
        at io.ballerina.runtime.api.Runtime.lambda$invokeMethodAsyncConcurrently$1(Runtime.java:122)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(Scheduler.java:611)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:317)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:284)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to reproduce:**
```ballerina
public function main() returns error? {
    string[] delFiles = [];
    ftp:Service ftpService = service object {
        remote function onFileChange(ftp:WatchEvent event) {
            io:println(event.toString());
            event.deletedFiles.forEach(function (string deletedFile) {
                  delFiles.push(deletedFile);
            });
        }
    };
    ftp:Listener ftpListener = check new ({
        protocol: ftp:FTP,
        host: "localhost",
        port: 21212,
        auth: {
            credentials: {username: "in", password: "wso2123"}
        },
        path: "/",
        pollingInterval: 2,
        fileNamePattern: "(.*).txt"
    });
    check ftpListener.attach(ftpService);
    check ftpListener.'start();
    runtime:registerListener(ftpListener);
    runtime:sleep(2);
}
```
After running this, try to change some file in the ftp server to invoke the service.

When these are added in tests, apart from above, following exception can also be seen.
```
error: Index 2 out of bounds for length 2
[2022-03-16 17:28:33,215] SEVERE {b7a.log.crash} - class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.api.values.BMap (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.api.values.BMap are in unnamed module of loader 'app') 
java.lang.ClassCastException: class io.ballerina.runtime.internal.values.ErrorValue cannot be cast to class io.ballerina.runtime.api.values.BMap (io.ballerina.runtime.internal.values.ErrorValue and io.ballerina.runtime.api.values.BMap are in unnamed module of loader 'app')
        at io.ballerina.stdlib.ftp.client.FtpClientHelper$2.notifySuccess(FtpClientHelper.java:279)
        at io.ballerina.runtime.internal.scheduling.Scheduler.postProcess(Scheduler.java:383)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:332)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:283)
        at io.ballerina.runtime.internal.scheduling.Scheduler.start(Scheduler.java:270)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.runOnSchedule(TesterinaFunction.java:117)
        at org.ballerinalang.test.runtime.entity.TesterinaFunction.invoke(TesterinaFunction.java:53)
        at org.ballerinalang.test.runtime.BTestRunner.invokeTestFunction(BTestRunner.java:754)
        at org.ballerinalang.test.runtime.BTestRunner.executeFunction(BTestRunner.java:567)
        at org.ballerinalang.test.runtime.BTestRunner.lambda$executeTests$1(BTestRunner.java:402)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at org.ballerinalang.test.runtime.BTestRunner.executeTests(BTestRunner.java:390)
        at org.ballerinalang.test.runtime.BTestRunner.execute(BTestRunner.java:288)
        at org.ballerinalang.test.runtime.BTestRunner.runTest(BTestRunner.java:135)
        at org.ballerinalang.test.runtime.util.TesterinaUtils.executeTests(TesterinaUtils.java:90)
```

**Affected Versions:**
2.2.0

**Comment by dilanSachi** [comment]
Apparently this issue is due to the following code.
```ballerina
delFiles.push(deletedFile);
```
Once it is removed or `delFiles` is created in module level, programme works correctly.

**Comment by dilanSachi** [comment]
Will check on the case further and report on the lang issues
