### ISSUE TITLE
`bal grpc` throws bad sad with an NPE

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-standard-library#2942]
Just run `bal grpc` anywhere. Here is the output I've got:

```
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-05-20 13:39:41,360] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at io.ballerina.stdlib.grpc.protobuf.cmd.GrpcCmd.execute(GrpcCmd.java:127)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

`2201.1.0`

**Comment by dilanSachi** [comment]
Added test cases. Hence closing.
