### ISSUE TITLE
GraphiQL client is not compatible with Windows

### ISSUE THREAD

**Issue by Nuvindu** [ballerina-platform/ballerina-standard-library#3029]
**Description:**

When I tried to run the following code in Windows 10, it produced an error in GraphiQL. The same code executed properly in Ubuntu 20.04.

```ballerina
import ballerina/graphql;

@graphql:ServiceConfig {
    graphiql: {
        enable: true
    }
}
service on new graphql:Listener(9000) {
    
    resource function get greeting() returns string {
        return "Hello";
    }
}
```

The following error returned in the GraphiQL [link](http://localhost:9000/graphiql)
```
{
  "errors": {
    "message": "Failed to execute 'fetch' on 'Window': Failed to parse URL from http://0:0:0:0:0:0:0:1:9000/",
    "stack": "TypeError: Failed to execute 'fetch' on 'Window': Failed to parse URL from http://0:0:0:0:0:0:0:1:9000/\n    at https://unpkg.com/graphiql/graphiql.min.js:37:183349\n    at Generator.next (<anonymous>)\n    at https://unpkg.com/graphiql/graphiql.min.js:37:181931\n    at new Promise (<anonymous>)\n    at o (https://unpkg.com/graphiql/graphiql.min.js:37:181676)\n    at https://unpkg.com/graphiql/graphiql.min.js:37:183300\n    at https://unpkg.com/graphiql/graphiql.min.js:37:180814\n    at https://unpkg.com/graphiql/graphiql.min.js:37:10346\n    at Id (https://unpkg.com/react-dom/umd/react-dom.production.min.js:165:137)\n    at Xb (https://unpkg.com/react-dom/umd/react-dom.production.min.js:200:284)"
  }
}
```

**Comment by ThisaruGuruge** [comment]
This is related to #3030
