### ISSUE TITLE
GraalVM native-image build is not working for in-memory websubhub sample

### ISSUE THREAD

**Issue by ayeshLK** [ballerina-platform/ballerina-standard-library#3458]
**Description:**
When building the native-image for in-memory websubhub [1] sample got following error at compile time. 
```sh
Error: Non-reducible loop requires too much duplication. Setting MaxDuplicationFactor to a value higher than 40.0 may resolve this.
Detailed message:
Call path from entry point to ballerina.in_memory_hub$0046dispatcher/1.dispatcher.syncDispatcherState(Strand): 
	at ballerina.in_memory_hub$0046dispatcher.1.dispatcher.syncDispatcherState(dispatcher.bal)
	at ballerina.in_memory_hub.1.start_hub.$syncDispatcherState$lambda$_0$(start_hub.bal:24)
	at ballerina.in_memory_hub.1.start_hub$$Lambda$944/0x00000007c2041040.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.concurrent.LinkedBlockingQueue$LBQSpliterator.tryAdvance(LinkedBlockingQueue.java:930)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:203)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback.handle(ReferenceCountedOpenSslClientContext.java:256)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS_ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback_handle_e21486683ddb969ec67d269d0970fda063b7e350(generated:0)
```
Since the error describes that we need to increase `-H:MaxDuplicationFactor` configuration, ran the build again after setting `-H:MaxDuplicationFactor` configuration to 800+ value. Then got the following error:
```sh
Error: Number of elements in a node list too high: 65537
Detailed message:
Call path from entry point to ballerina.in_memory_hub$0046dispatcher/1.dispatcher.syncDispatcherState(Strand): 
	at ballerina.in_memory_hub$0046dispatcher.1.dispatcher.syncDispatcherState(dispatcher.bal)
	at ballerina.in_memory_hub.1.start_hub.$syncDispatcherState$lambda$_0$(start_hub.bal:24)
	at ballerina.in_memory_hub.1.start_hub$$Lambda$948/0x00000007c200c440.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.util.ServiceLoader$ProviderSpliterator.tryAdvance(ServiceLoader.java:1492)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:203)
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback.handle(ReferenceCountedOpenSslClientContext.java:256)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY_Nonvirtual_ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback_handle_e21486683ddb969ec67d269d0970fda063b7e350(generated:0)
``` 

Related JAR file can be found here [2].

[1] - https://github.com/ballerina-platform/module-ballerina-websubhub/tree/main/examples/in-memory-hub/hub
[2] - https://drive.google.com/file/d/174W-4RozmijPYT05vO5fCmfeYnb4mWqz/view?usp=sharing

**Comment by TharmiganK** [comment]
`MaxDuplicationFactor` is used to resolve the non-reducible loops in the analysis. This value depends on the ballerina sample we are trying to build. Seems like this happens due to how ballerina is designed. 

The second error is related to the node list limit enforced by the pointsto algorithm used in native-image build. This is expected as we have increased the number of duplications.

In this example, we have several isolated variables and methods and used lock statements to update/return the values associated with this isolated variables in the isolated methods. When we remove this isolated and lock usages from the sample. The sample is building without any error (-H:MaxDuplicationFactor=25).

@warunalakshitha FYI
