### ISSUE TITLE
Add native image build support for XSLT

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-standard-library#3462]
**Description:**

XSLT module level tests failed with the following error when used with GraalVM native-image tool:

```console
Fatal error: java.lang.InternalError: Enclosing method not found
        at java.base/java.lang.Class.getEnclosingMethod(Class.java:1296)
        at java.base/sun.reflect.generics.scope.ClassScope.computeEnclosingScope(ClassScope.java:50)
        at java.base/sun.reflect.generics.scope.AbstractScope.getEnclosingScope(AbstractScope.java:77)
        at java.base/sun.reflect.generics.scope.AbstractScope.lookup(AbstractScope.java:95)
        at java.base/sun.reflect.generics.factory.CoreReflectionFactory.findTypeVariable(CoreReflectionFactory.java:110)
        at java.base/sun.reflect.generics.visitor.Reifier.visitTypeVariableSignature(Reifier.java:165)
        at java.base/sun.reflect.generics.tree.TypeVariableSignature.accept(TypeVariableSignature.java:43)
        at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
        at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
        at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
        at java.base/sun.reflect.generics.repository.ClassRepository.computeSuperclass(ClassRepository.java:104)
        at java.base/sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:86)
        at java.base/java.lang.Class.getGenericSuperclass(Class.java:949)
        at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ReflectionDataBuilder.query(ReflectionDataBuilder.java:702)
        at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ReflectionDataBuilder.registerTypesForClass(ReflectionDataBuilder.java:412)
        at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ReflectionDataBuilder.processMethodMetadata(ReflectionDataBuilder.java:267)
        at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ReflectionDataBuilder.duringAnalysis(ReflectionDataBuilder.java:187)
        at org.graalvm.nativeimage.builder/com.oracle.svm.reflect.hosted.ReflectionFeature.duringAnalysis(ReflectionFeature.java:238)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:734)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:78)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:734)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.runAnalysis(PointsToAnalysis.java:755)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:731)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:564)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

According to this issue in graal repository : https://github.com/oracle/graal/issues/1438, seems like this error occurred due to an axiom class and fixed in `1.3.0`. So we need to update the axiom version used in XSLT to `1.4.0`(latest version) to check whether this resolves the issue or not. 

Since lang-runtime also has this axiom dependency, this have to be done after lang-runtime updates the version. Lang issue : https://github.com/ballerina-platform/ballerina-lang/issues/37844

**Describe your task(s)**

Update the axiom version used in XSLT to `1.4.0`(latest version) after lang-runtime updates this dependency.

**Comment by TharmiganK** [comment]
After the axiom update, we were able to build the native image but the image failed at runtime : 
```console
WARNING: Unable to load manifest for StAX implementation at resource:/
error: com.oracle.svm.core.jdk.UnsupportedFeatureError {"message":"No classes have been predefined during 
the image build to load from bytecodes at runtime."}
        at ballerina.xslt/2:transform(natives.bal:30)
           user.xslt_test/0:readFromFile(read-from-file.bal:104)
           user.xslt_test/0:testReadFromFile(read-from-file.bal:25)
           user.xslt_test/0:main(main.bal:3)
```

And found a similar issue in the graal repo : [`XSLT causes the executable to crash at runtime #3811`](https://github.com/oracle/graal/issues/3811)
