### ISSUE TITLE
Investigate on OOM issue when checking graalvm native image compatibility with gRPC

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-standard-library#3479]
**Description:**
This usually results in `137` status in the compile stage,
```
[6/7] Compiling methods...    [**********Error: Image build request failed with exit status 137
```
Found the following when running on macOS
```
GC warning: 581.4s spent in 53 GCs during the last stage, taking up 54.98% of the time.
            Please ensure more than 9.62GB of memory is available for Native Image
            to reduce GC overhead and improve image build time.

Fatal error: org.graalvm.compiler.debug.GraalError: java.lang.OutOfMemoryError: Java heap space
        at method: Object ballerina.grpc/1.$value$$anonType$_0.ServerReflectionInfo(Strand, BObject, StreamValue)  [Direct call from Object $value$$anonType$_0.call(Strand, String, Object[])]
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:1435)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:1370)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:337)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

This happened after adding a new feature related to server reflection in gRPC - https://github.com/ballerina-platform/module-ballerina-grpc/pull/1015

**Comment by dilanSachi** [comment]
According to the error msg, the issue is related to the `ServerReflectionInfo` function inside the dynamic service `reflectionService` in here [1].

When I broke the function into several parts and reduced the function line length, the native image for the bbes and module tests can be built.

Will confirm this by running all the module tests.

[1] https://github.com/ballerina-platform/module-ballerina-grpc/blob/d4a979c1906dab2a1e44c3695d5f1c64a8342b6b/ballerina/service_endpoint.bal#L101

**Comment by dilanSachi** [comment]
With the reformatting of the code, was able to successfully complete the module level tests and bbes as well.
