### ISSUE TITLE
Exception throwing when generating client sample code from the proto file.

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3654]
**Description:**
Proto file link: https://github.com/wso2/apk/blob/main/management-server/api/apids.proto

When you generate the client stub and client sample code. Following exception throws,

```
[2022-11-15 23:18:29,981] SEVERE {b7a.log.crash} - Index -1 out of bounds for length 0
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.remove(ArrayList.java:536)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.getFieldNodes(ClientSampleSyntaxTreeUtils.java:338)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.handleMessageTypes(ClientSampleSyntaxTreeUtils.java:383)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.getFieldPatternNode(ClientSampleSyntaxTreeUtils.java:367)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.getFieldNodes(ClientSampleSyntaxTreeUtils.java:335)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.handleMessageTypes(ClientSampleSyntaxTreeUtils.java:383)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.getFieldPatternNode(ClientSampleSyntaxTreeUtils.java:367)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.handleRepeatedTypes(ClientSampleSyntaxTreeUtils.java:391)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.getFieldPatternNode(ClientSampleSyntaxTreeUtils.java:365)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.getFieldNodes(ClientSampleSyntaxTreeUtils.java:335)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.getInputDeclarationStatement(ClientSampleSyntaxTreeUtils.java:321)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.addUnaryCallMethodBody(ClientSampleSyntaxTreeUtils.java:145)
	at io.ballerina.stdlib.grpc.builder.syntaxtree.utils.ClientSampleSyntaxTreeUtils.generateSyntaxTreeForClientSample(ClientSampleSyntaxTreeUtils.java:116)
	at io.ballerina.stdlib.grpc.builder.BallerinaFileBuilder.computeSourceContent(BallerinaFileBuilder.java:287)
	at io.ballerina.stdlib.grpc.builder.BallerinaFileBuilder.build(BallerinaFileBuilder.java:128)
	at io.ballerina.stdlib.grpc.protobuf.cmd.GrpcCmd.generateBalFile(GrpcCmd.java:317)
	at io.ballerina.stdlib.grpc.protobuf.cmd.GrpcCmd.execute(GrpcCmd.java:165)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Steps to reproduce:**
Execute gRPC CLI command in client mode 

**Affected Versions:**
2201.3.0-rc2

**Comment by dilanSachi** [comment]
The exception is due to empty records.
https://github.com/wso2/apk/blob/main/management-server/api/apids.proto#L65
