### ISSUE TITLE
Get NPE when we add optional value or optional field to the entity record

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#3744]
**Description:**
```
@persist:Entity {
    key: ["needId"]
}
public type MedicalNeed record {|
    @persist:AutoIncrement
    readonly int needId = -1;

    int itemId;
    int beneficiaryId;
    time:Civil period;
    string urgency;
    int quantity;
    int xyz;
|};

@persist:Entity {
    key: ["itemId"]
}
public type MedicalItem record {|
    readonly int itemId;
    string name;
    string 'type;
    string unit;
    MedicalNeed mn?;
|};
```
In the above sample, if we make an optional value or optional field, we got following NPE error,

```
[2022-12-01 14:18:39,570] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.persist.utils.SqlScriptGenerationUtils.createColumnsScript(SqlScriptGenerationUtils.java:197)
        at io.ballerina.persist.utils.SqlScriptGenerationUtils.generateFieldsQuery(SqlScriptGenerationUtils.java:103)
        at io.ballerina.persist.utils.SqlScriptGenerationUtils.generateTableQuery(SqlScriptGenerationUtils.java:93)
        at io.ballerina.persist.utils.SqlScriptGenerationUtils.generateSqlScript(SqlScriptGenerationUtils.java:80)
        at io.ballerina.persist.utils.SqlScriptGenerationUtils.generateSqlScript(SqlScriptGenerationUtils.java:66)
        at io.ballerina.persist.cmd.Push.execute(Push.java:148)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Comment by niveathika** [comment]
This is fixed in https://github.com/ballerina-platform/module-ballerina-persist/pull/85
