### ISSUE TITLE
NullPointerException when calling resource function from within `do` block

### ISSUE THREAD

**Issue by kaneeldias** [ballerina-platform/ballerina-standard-library#3951]
**Description:**
I am getting a bad sad error when trying to compile the code below

```ballerina
_ = check from MedicalItem itemx in mcClient->/medicalItems.get()
    where itemx.'type == "type2"
    do {
        MedicalItemUpdate updatex = {unit: "kg"};
        _ = check mcClient->/medicalItems/[itemx.itemId].put(updatex);
    };
```

```
[2023-01-18 17:43:12,963] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.visit(BIROptimizer.java:159)
        at org.wso2.ballerinalang.compiler.bir.model.BIRNode$BIRBasicBlock.accept(BIRNode.java:466)
        at org.wso2.ballerinalang.compiler.bir.optimizer.BIROptimizer$RHSTempVarOptimizer.lambda$visit$3(BIROptimizer.java:121)
        ...
```

The error seems to occur at `_ = check mcClient->/medicalItems/[itemx.itemId].put(updatex);`

The same code compiles fine when I move the line in question out of the do block

**Comment by kaneeldias** [comment]
Closing as issue is a duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/38839
