### ISSUE TITLE
[Code Generator] Map returns from getDescriptorMap() function has duplicate keys

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-standard-library#44]
**Description:**
When the proto contract file and its dependent proto file imports the same proto file. the proto descriptor value of the imported proto file is duplicated in the `getDescriptorMap()`. This leads to NPE when compiling the source code,

```
[2020-10-07 13:47:35,684] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:1944)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangRecordLiteral.accept(BLangRecordLiteral.java:72)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeExpr(CodeAnalyzer.java:2604)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.visit(CodeAnalyzer.java:572)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangReturn.accept(BLangReturn.java:44)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CodeAnalyzer.analyzeNode(CodeAnalyzer.java:313)
```

**Comment by dilanSachi** [comment]
The proto descriptor value is not duplicated anymore. Therefore this issue is not applicable now.
