### ISSUE TITLE
[HTTP] ResponseCacheControlObj returns null strand

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-standard-library#502]
**Description:**
The ResponseCacheControlObj returns null for getStrand() method call. 

**Steps to reproduce**
In the ballerina source, add the following code inside the ResponseCacheControlObj object in this:
https://github.com/ballerina-platform/ballerina-lang/blob/41a42b283f3fa6395c641c7d549721f5216d2b30/stdlib/http/src/main/ballerina/src/http/caching/caching_commons.bal#L152

```
public function __init() {
        future<int> accumulator = start sum(2, 4);
    }
```
add relevant 'sum' function inside the file such as,
```
function sum(int a, int b) returns int {
    return a + b;
}
```
Modify the createObjectValues method in BallerinaValues.java in here:
https://github.com/ballerina-platform/ballerina-lang/blob/41a42b283f3fa6395c641c7d549721f5216d2b30/bvm/ballerina-runtime/src/main/java/org/ballerinalang/jvm/BallerinaValues.java#L89

change it as follows,
```
try {
     return valueCreator.createObjectValue(objectTypeName, null, null, null, fields)
} catch (Exception ex) {
     ex.printStackTrace();
     throw ex;
}
```
Run the test case NotSoBasicWorkerTest. testForkJoinWorkersWithNonBlockingConnector: 
https://github.com/ballerina-platform/ballerina-lang/blob/41a42b283f3fa6395c641c7d549721f5216d2b30/tests/jballerina-unit-test/src/test/java/org/ballerinalang/test/worker/NotSoBasicWorkerTest.java#L152

**Stack trace:**
```
 java.lang.NullPointerException
        at ballerina.http.$value$ResponseCacheControl.__init(caching/caching_commons.bal:170)
        at ballerina.http.$value$ResponseCacheControl.call(caching/caching_commons.bal)
        at ballerina.http.$value$ResponseCacheControl.$__init$(caching/caching_commons.bal:158)
        at ballerina.http.$value$ResponseCacheControl.call(caching/caching_commons.bal)
        at ballerina.http.___init.createObjectValue(http)
        at org.ballerinalang.jvm.BallerinaValues.createObjectValue(BallerinaValues.java:90)
        at org.ballerinalang.net.http.caching.ResponseCacheControlObj.<init>(ResponseCacheControlObj.java:54)
        at org.ballerinalang.net.http.HttpUtil.populateInboundResponse(HttpUtil.java:780)
        at org.ballerinalang.net.http.HttpUtil.createResponseStruct(HttpUtil.java:1169)
        at org.ballerinalang.net.http.actions.httpclient.AbstractHTTPAction$HTTPClientConnectorListener.onMessage(AbstractHTTPAction.java:434)
        at org.wso2.transport.http.netty.contractimpl.DefaultHttpResponseFuture.notifyHttpListener(DefaultHttpResponseFuture.java:110)
        at org.wso2.transport.http.netty.contractimpl.sender.states.ReceivingHeaders.readInboundResponseHeaders(ReceivingHeaders.java:77)
        at org.wso2.transport.http.netty.contractimpl.common.states.SenderReqRespStateManager.readInboundResponseHeaders(SenderReqRespStateManager.java:54)
        at org.wso2.transport.http.netty.contractimpl.sender.states.RequestCompleted.readInboundResponseHeaders(RequestCompleted.java:67)
        at org.wso2.transport.http.netty.contractimpl.common.states.SenderReqRespStateManager.readInboundResponseHeaders(SenderReqRespStateManager.java:54)
        at org.wso2.transport.http.netty.contractimpl.sender.TargetHandler.channelRead(TargetHandler.java:85)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:308)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:422)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

```
Found while extracting the current strand for the fix in ballerina-platform/ballerina-lang#21018 

**Affected Versions:**
1.2.0-SNAPSHOT

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
ballerina-platform/ballerina-lang#21018 

**Suggested Labels (optional):**
Area/StandardLibs

**Comment by daneshk** [comment]
This may not be valid anymore with the JDK 21 effort. Hence, closing this issue. Please reopen if we still need to attend.
